---
name: Create packages and test installation

on:
  pull_request:
  
  workflow_dispatch:

jobs:
  centos7:
    name: Build CentOS 7 rpms
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/noarch/nagios-plugin-secret-store-*-1.noarch.rpm
  centos7-install:
    name: Install CentOS 7 rpms
    needs: centos7
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rpms7
      - name: Install generated rpms
        run: |
          yum localinstall -y nagios-plugin-secret-store-*.rpm
