name: Create packages and release

on:
  push:
    tags:
      - "v*"
      
  workflow_dispatch:

jobs:
  centos7:
    name: Build CentOS 7 rpms
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v2
        with:
          name: rpms7
          path: |
            build/RPMS/noarch/nagios-plugin-secret-store-*-1.noarch.rpm
            build/SRPMS/nagios-plugin-secret-store-*-1.src.rpm
        
  create-release:
    name: Create release
    needs: [centos7]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

  release7:
    name: Upload CentOS 7 release artefacts
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rpms7
      - name: Find package name
        id: package_name_centos7
        run: |
          rpm_path=$(find . -name 'nagios-plugin-secret-store-*-1.noarch.rpm')
          rpm_name=$(basename $rpm_path)
          src_path=$(find . -name 'nagios-plugin-secret-store-*-1.src.rpm')
          src_name=$(basename $src_path)
          echo ::set-output name=rpm_path::$rpm_path
          echo ::set-output name=rpm_name::$rpm_name
          echo ::set-output name=src_path::$src_path
          echo ::set-output name=src_name::$src_name
      - name: Upload nagios-plugin-secret-store rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ steps.package_name_centos7.outputs.rpm_path }}
          asset_name: ${{ steps.package_name_centos7.outputs.rpm_name }}
          asset_content_type: application/octet-stream
      - name: Upload nagios-plugin-secret-store source rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ steps.package_name_centos7.outputs.src_path }}
          asset_name: ${{ steps.package_name_centos7.outputs.src_name }}
          asset_content_type: application/octet-stream
